import Mathlib

/-!
# Tematika 01 — "A valós számtest" (the real number field)

**Syllabus item.**  *A valós számtest.*

**Categorical reading.**  A "number domain to work over" is an *object of a
category of rings*, singled out by a universal property.  Calculus I and this
library make different choices of ground object, and the two choices are
related by comparison maps:

* Calculus I works over `ℝ`, which is *the* conditionally complete linearly
  ordered field, up to a **unique** isomorphism — a universal property in the
  category whose objects are such fields and whose morphisms are ordered ring
  maps (`Tematika.Ground.real_unique_up_to_unique_iso`);
* the library works over a finite field `K` with `Fintype.card K = 2 ^ n`,
  determined up to isomorphism by its cardinality
  (`Tematika.Ground.finite_field_unique_of_card`) — but *not* up to a unique
  isomorphism: the comparison is a torsor under the Galois group generated by
  the Frobenius `x ↦ x ^ 2`, and that extra automorphism is exactly the
  structure the library exploits and Calculus I does not have;
* both live under the same initial object `ℤ` of `CommRingCat`
  (`Tematika.Ground.int_isInitial`, `Tematika.Ground.subsingleton_ringHom_int`),
  so the arithmetic of the two courses is the image of one and the same
  arithmetic under the two unique structure maps.

`ℝ` re-enters the library's own proof as the target of the positivity
argument: the counts are compared inside `ℝ ⊆ ℂ` (see `Tematika/Extrema.lean`).
-/

namespace Tematika.Ground

open CategoryTheory

/-- **The real field is a universal object.**  Any two conditionally complete
linearly ordered fields are isomorphic by a *unique* ordered ring isomorphism.
This is the categorical content of "a valós számtest": `ℝ` is not a set one
chooses but an object determined by a universal property. -/
theorem real_unique_up_to_unique_iso (β γ : Type*)
    [ConditionallyCompleteLinearOrderedField β] [ConditionallyCompleteLinearOrderedField γ] :
    Nonempty (β ≃+*o γ) ∧ Subsingleton (β ≃+*o γ) :=
  ⟨⟨LinearOrderedField.inducedOrderRingIso β γ⟩, inferInstance⟩

/-- The library's ground object satisfies the analogous statement with the
order dropped: a finite field is determined up to isomorphism by its
cardinality.  Uniqueness of the isomorphism fails — the discrepancy is the
Galois group, generated by the Frobenius. -/
theorem finite_field_unique_of_card {K K' : Type*} [Field K] [Field K']
    [Fintype K] [Fintype K'] (h : Fintype.card K = Fintype.card K') :
    Nonempty (K ≃+* K') :=
  ⟨FiniteField.ringEquivOfCardEq h⟩

/-- The Frobenius: the automorphism of the library's ground object that has no
counterpart over `ℝ`.  In characteristic two it is the squaring map. -/
theorem frobenius_apply_charTwo {K : Type*} [CommRing K] [ExpChar K 2] (x : K) :
    frobenius K 2 x = x ^ 2 := rfl

/-- `ℤ` is initial in `CommRingCat`: the common base of both ground objects. -/
theorem int_isInitial : Nonempty (Limits.IsInitial (CommRingCat.of ℤ)) :=
  ⟨CommRingCat.zIsInitial⟩

/-- The elementwise form of initiality: every commutative ring — `ℝ` and the
library's `K` alike — receives exactly one ring map from `ℤ`. -/
theorem subsingleton_ringHom_int (R : Type*) [CommRing R] : Subsingleton (ℤ →+* R) :=
  ⟨fun f g => RingHom.ext_int f g⟩

end Tematika.Ground
