import Mathlib

/-!
# Tilings and patterns as a way of reasoning about linear algebra

This module backs the "drawing tilings" half of `patterns.tex`.  The slogan is

> a linear map is a re-tiling of space, and the determinant is the factor by
> which one tile grows.

Four groups of statements:

1. **A lattice tiles the plane.**  The translates of the fundamental
   parallelogram of a basis cover the plane exactly once
   (`plane_is_tiled_by_lattice`), all tiles have the same area
   (`tiles_are_congruent`) and that area is `|det|`
   (`tile_area_eq_abs_det`).  If the determinant vanishes the "tile" is
   degenerate and nothing is tiled (`degenerate_no_tiling`).

2. **The determinant is the area scale factor** (`area_scales_by_det`), so
   `det (AB) = det A · det B` is "re-tile twice" (`det_mul_is_retiling`) and a
   shear — one step of Gaussian elimination — slides a tile without changing
   its area (`shear_preserves_area`, `row_operation_preserves_det`).

3. **The crystallographic restriction.**  A symmetry of a lattice has an
   integer matrix, hence an integer trace; a rotation has trace `2 cos θ`;
   therefore `2 cos θ ∈ {0, ±1, ±2}` and only 1-, 2-, 3-, 4- and 6-fold
   rotations exist (`two_cos_of_lattice_rotation`, `cos_of_lattice_rotation`).
   The purely algebraic form, proved from the `2 × 2` Cayley–Hamilton identity
   and a trace recursion, is `abs_trace_le_two` and `pow_twelve_eq_one`.

4. **The point group of the square lattice** is the dihedral group of order 8
   (`lattice_isometry_cases`, `pointGroupSquare_card`).
-/

namespace Tiling

open Matrix MeasureTheory
open scoped BigOperators Pointwise

/-! ## 1. A lattice tiles the plane -/

section LatticeTiling

variable {ι : Type*} [Fintype ι]

/-- **The plane is tiled by a lattice.**  For a basis `b` of `ℝⁿ`, every point of
the space lies in exactly one translate of the half-open fundamental
parallelogram `{∑ tᵢ bᵢ | 0 ≤ tᵢ < 1}` by a lattice vector.  This is the precise
sense in which the pictures of a lattice tiling are correct. -/
theorem plane_is_tiled_by_lattice (b : Module.Basis ι ℝ (ι → ℝ)) (x : ι → ℝ) :
    ∃! v : Submodule.span ℤ (Set.range b), v +ᵥ x ∈ ZSpan.fundamentalDomain b :=
  ZSpan.exist_unique_vadd_mem_fundamentalDomain b x

/-- All tiles of the tiling are translates of one another, hence have the same area. -/
theorem tiles_are_congruent (b : Module.Basis ι ℝ (ι → ℝ)) (v : ι → ℝ) :
    volume (v +ᵥ ZSpan.fundamentalDomain b) = volume (ZSpan.fundamentalDomain b) :=
  measure_vadd _ _ _

/-- **The area of a tile is the absolute value of the determinant.** -/
theorem tile_area_eq_abs_det [DecidableEq ι] (b : Module.Basis ι ℝ (ι → ℝ)) :
    volume (ZSpan.fundamentalDomain b) = ENNReal.ofReal |(Matrix.of ⇑b).det| :=
  ZSpan.volume_fundamentalDomain b

/-- A worked two-dimensional instance: the tile of the lattice generated by
`(a, b)` and `(c, d)` has area `|ad - bc|`. -/
theorem tile_area_fin_two (b : Module.Basis (Fin 2) ℝ (Fin 2 → ℝ)) :
    volume (ZSpan.fundamentalDomain b)
      = ENNReal.ofReal |b 0 0 * b 1 1 - b 0 1 * b 1 0| := by
  rw [ZSpan.volume_fundamentalDomain b, Matrix.det_fin_two]
  rfl

/-- **A degenerate tile tiles nothing.**  If the determinant vanishes, the two
generating vectors are dependent: there is a nonzero vector killed by the
matrix, so the "parallelogram" is flat. -/
theorem degenerate_no_tiling {n : Type*} [Fintype n] [DecidableEq n]
    (A : Matrix n n ℝ) (h : A.det = 0) : ∃ v : n → ℝ, v ≠ 0 ∧ A *ᵥ v = 0 := by
  exact Matrix.exists_mulVec_eq_zero_iff.2 h

end LatticeTiling

/-! ## 2. The determinant is the area scale factor -/

section AreaScaling

variable {n : Type*} [Fintype n]

/-- **A linear map re-tiles space, and the determinant is the scale factor.** -/
theorem area_scales_by_det (f : (n → ℝ) →ₗ[ℝ] (n → ℝ)) (s : Set (n → ℝ)) :
    volume (f '' s) = ENNReal.ofReal |LinearMap.det f| * volume s :=
  Measure.addHaar_image_linearMap volume f s

/-- Doing two re-tilings multiplies the scale factors: this is the picture proof of
`det (A B) = det A · det B`. -/
theorem det_mul_is_retiling [DecidableEq n] (A B : Matrix n n ℝ) : (A * B).det = A.det * B.det :=
  Matrix.det_mul A B

/-- One step of Gaussian elimination (add a multiple of one row to another) is a
shear; it slides the tile and does not change its area. -/
theorem row_operation_preserves_det [DecidableEq n] (A : Matrix n n ℝ) {i j : n} (h : i ≠ j) (c : ℝ) :
    (A.updateRow i (A i + c • A j)).det = A.det :=
  Matrix.det_updateRow_add_smul_self A h c

/-- The plane shear `(x, y) ↦ (x + c y, y)` has determinant `1`: sliding a tile
sideways does not change its area. -/
theorem shear_det (c : ℝ) : (!![1, c; 0, 1] : Matrix (Fin 2) (Fin 2) ℝ).det = 1 := by
  simp [Matrix.det_fin_two_of]

/-- Hence the shear preserves the area of every set: the classical "same base, same
height" picture for the area of a parallelogram. -/
theorem shear_preserves_area (c : ℝ) (s : Set (Fin 2 → ℝ)) :
    volume (Matrix.toLin' (!![1, c; 0, 1] : Matrix (Fin 2) (Fin 2) ℝ) '' s) = volume s := by
  rw [area_scales_by_det, LinearMap.det_toLin', shear_det]
  simp

end AreaScaling

/-! ## 3. The crystallographic restriction -/

section Crystallographic

/-- The Cayley–Hamilton identity in size two, proved entry by entry.  It is the
engine of the whole section: it turns "`A` has finite order" into a linear
recursion for the traces of the powers of `A`. -/
theorem cayley_hamilton_two {R : Type*} [CommRing R] (A : Matrix (Fin 2) (Fin 2) R) :
    A * A = A.trace • A - A.det • (1 : Matrix (Fin 2) (Fin 2) R) := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Matrix.mul_apply, Fin.sum_univ_two, Matrix.smul_apply,
      Matrix.trace_fin_two, Matrix.det_fin_two] <;> ring

/-- The trace recursion `sₖ₊₂ = t sₖ₊₁ − sₖ` for a unimodular `2 × 2` matrix,
where `sₖ = tr (Aᵏ)` and `t = tr A`. -/
theorem trace_pow_rec {R : Type*} [CommRing R] (A : Matrix (Fin 2) (Fin 2) R)
    (hdet : A.det = 1) (k : ℕ) :
    (A ^ (k + 2)).trace = A.trace * (A ^ (k + 1)).trace - (A ^ k).trace := by
  have hA : A * A = A.trace • A - (1 : Matrix (Fin 2) (Fin 2) R) := by
    rw [cayley_hamilton_two A, hdet, one_smul]
  have : A ^ (k + 2) = A ^ k * (A * A) := by rw [pow_succ, pow_succ, mul_assoc]
  rw [this, hA, Matrix.mul_sub, Matrix.mul_smul, Matrix.mul_one, Matrix.trace_sub,
    Matrix.trace_smul, smul_eq_mul, ← pow_succ]

/-- An integer matrix of determinant `1` and trace at least `3` has infinite order:
the traces of its powers increase strictly. -/
theorem no_finite_order_of_trace_ge_three (A : Matrix (Fin 2) (Fin 2) ℤ)
    (hdet : A.det = 1) (ht : 3 ≤ A.trace) (k : ℕ) :
    2 ≤ (A ^ k).trace ∧ (A ^ k).trace < (A ^ (k + 1)).trace := by
  induction k with
  | zero =>
      refine ⟨by simp [Matrix.trace_one], ?_⟩
      simpa [Matrix.trace_one] using ht
  | succ k ih =>
      obtain ⟨h2, hlt⟩ := ih
      have hrec := trace_pow_rec A hdet k
      refine ⟨by omega, ?_⟩
      have h3 : (3 : ℤ) ≤ (A ^ (k + 1)).trace := by omega
      nlinarith [mul_le_mul_of_nonneg_right ht (le_trans (by norm_num) h3)]

/-- One half of the bound: a unimodular integer matrix of finite order has trace at
most `2`.  (If the trace were `≥ 3`, the traces of the powers would grow.) -/
theorem trace_le_two_of_pow_eq_one (B : Matrix (Fin 2) (Fin 2) ℤ) (hdet : B.det = 1)
    {m : ℕ} (hm : 1 ≤ m) (hB : B ^ m = 1) : B.trace ≤ 2 := by
  by_contra hcon
  push_neg at hcon
  have h3 : 3 ≤ B.trace := by omega
  obtain ⟨k, rfl⟩ : ∃ k, m = k + 1 := ⟨m - 1, by omega⟩
  obtain ⟨h2, hlt⟩ := no_finite_order_of_trace_ge_three B hdet h3 k
  have hone : (B ^ (k + 1)).trace = 2 := by rw [hB]; simp [Matrix.trace_one]
  omega

/-- Negating a matrix of finite order again gives a matrix of finite order. -/
theorem neg_pow_eq_one (A : Matrix (Fin 2) (Fin 2) ℤ) {n : ℕ} (hA : A ^ n = 1) :
    (-A) ^ (2 * n) = 1 := by
  have hsq : (-A) ^ 2 = A ^ 2 := by noncomm_ring
  rw [pow_mul, hsq, ← pow_mul, mul_comm, pow_mul, hA, one_pow]

/-- The determinant is unchanged by negation in even size. -/
theorem det_neg_two (A : Matrix (Fin 2) (Fin 2) ℤ) (hdet : A.det = 1) : (-A).det = 1 := by
  rw [show (-A) = (-1 : ℤ) • A by simp, Matrix.det_smul, hdet]
  norm_num

/-- **The trace of a finite-order unimodular integer matrix is at most `2` in absolute
value.**  This is the algebraic form of the crystallographic restriction. -/
theorem abs_trace_le_two (A : Matrix (Fin 2) (Fin 2) ℤ) (hdet : A.det = 1)
    {n : ℕ} (hn : 1 ≤ n) (hA : A ^ n = 1) : |A.trace| ≤ 2 := by
  have hup : A.trace ≤ 2 := trace_le_two_of_pow_eq_one A hdet hn hA
  have hlow : (-A).trace ≤ 2 :=
    trace_le_two_of_pow_eq_one (-A) (det_neg_two A hdet) (by omega) (neg_pow_eq_one A hA)
  rw [Matrix.trace_neg] at hlow
  rw [abs_le]
  omega

/-- The set of possible traces, listed. -/
theorem trace_mem_five_values (A : Matrix (Fin 2) (Fin 2) ℤ) (hdet : A.det = 1)
    {n : ℕ} (hn : 1 ≤ n) (hA : A ^ n = 1) :
    A.trace = -2 ∨ A.trace = -1 ∨ A.trace = 0 ∨ A.trace = 1 ∨ A.trace = 2 := by
  have := abs_trace_le_two A hdet hn hA
  rw [abs_le] at this
  omega

/-- **Crystallographic restriction, geometric form.**  If the rotation by `θ` maps a
lattice to itself — that is, if its matrix in a lattice basis has integer
entries — then `2 cos θ` is an integer of absolute value at most `2`. -/
theorem two_cos_of_lattice_rotation (t : ℝ) (A : Matrix (Fin 2) (Fin 2) ℤ)
    (hA : A.map (Int.cast) = !![Real.cos t, -Real.sin t; Real.sin t, Real.cos t]) :
    ∃ k : ℤ, 2 * Real.cos t = (k : ℝ) ∧ |k| ≤ 2 := by
  have h00 : ((A 0 0 : ℤ) : ℝ) = Real.cos t := by
    have := congrArg (fun M => M 0 0) hA
    simpa [Matrix.map_apply] using this
  have h11 : ((A 1 1 : ℤ) : ℝ) = Real.cos t := by
    have := congrArg (fun M => M 1 1) hA
    simpa [Matrix.map_apply] using this
  have h : ((A.trace : ℤ) : ℝ) = 2 * Real.cos t := by
    rw [Matrix.trace_fin_two]
    push_cast
    rw [h00, h11]
    ring
  refine ⟨A.trace, h.symm, ?_⟩
  have hb : |((A.trace : ℤ) : ℝ)| ≤ ((2 : ℤ) : ℝ) := by
    rw [h, abs_mul, abs_two]
    have hc := Real.abs_cos_le_one t
    push_cast
    linarith
  exact_mod_cast hb

/-- Consequently the cosine of the rotation angle is one of five values, i.e. the
rotation is by a multiple of `60°` or of `90°`: only 1-, 2-, 3-, 4- and 6-fold
symmetry axes occur in a lattice.  (There is no fivefold wallpaper pattern.) -/
theorem cos_of_lattice_rotation (t : ℝ) (A : Matrix (Fin 2) (Fin 2) ℤ)
    (hA : A.map (Int.cast) = !![Real.cos t, -Real.sin t; Real.sin t, Real.cos t]) :
    Real.cos t = -1 ∨ Real.cos t = -1/2 ∨ Real.cos t = 0 ∨ Real.cos t = 1/2 ∨
      Real.cos t = 1 := by
  obtain ⟨k, hk, hk2⟩ := two_cos_of_lattice_rotation t A hA
  have : k = -2 ∨ k = -1 ∨ k = 0 ∨ k = 1 ∨ k = 2 := by
    rw [abs_le] at hk2; omega
  rcases this with h | h | h | h | h <;> rw [h] at hk <;> push_cast at hk
  · exact Or.inl (by linarith)
  · exact Or.inr (Or.inl (by linarith))
  · exact Or.inr (Or.inr (Or.inl (by linarith)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (by linarith))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (by linarith))))

/-- If the trace is `2` then `A - 1` squares to zero, so the powers of `A` are
`1 + k(A-1)`; finite order then forces `A = 1`.  (Diagrammatically: a shear that
repeats to the identity is no shear at all.) -/
theorem eq_one_of_trace_two (A : Matrix (Fin 2) (Fin 2) ℤ) (hdet : A.det = 1)
    (htr : A.trace = 2) {n : ℕ} (hn : 1 ≤ n) (hA : A ^ n = 1) : A = 1 := by
  have hsq : A * A = (2 : ℤ) • A - 1 := by
    rw [cayley_hamilton_two A, hdet, htr, one_smul]
  have hN2 : (A - 1) * (A - 1) = 0 := by
    have hexp : (A - 1) * (A - 1) = A * A - A - A + 1 := by noncomm_ring
    rw [hexp, hsq, two_smul]
    abel
  have hpow : ∀ k : ℕ, A ^ k = 1 + (k : ℤ) • (A - 1) := by
    intro k
    induction k with
    | zero => simp
    | succ k ih =>
        have hA1 : A = 1 + (A - 1) := by abel
        rw [pow_succ, ih]
        nth_rewrite 2 [hA1]
        rw [mul_add, mul_one, add_mul, one_mul, smul_mul_assoc, hN2, smul_zero, add_zero]
        push_cast
        rw [add_smul, one_smul]
        abel
  have hzero : (n : ℤ) • (A - 1) = 0 := by
    have hone := hpow n
    rw [hA] at hone
    have h : (1 : Matrix (Fin 2) (Fin 2) ℤ) + 0 = 1 + (n : ℤ) • (A - 1) := by
      rw [add_zero]; exact hone
    exact (add_left_cancel h).symm
  have hsub : A - 1 = 0 := by
    ext i j
    have h := congrFun (congrFun hzero i) j
    simp only [Matrix.smul_apply, smul_eq_mul, Matrix.zero_apply] at h
    have hn0 : (n : ℤ) ≠ 0 := by exact_mod_cast (Nat.pos_of_ne_zero (by omega)).ne'
    simpa [Matrix.zero_apply] using (mul_eq_zero.mp h).resolve_left hn0
  have := sub_eq_zero.mp hsub
  exact this

/-- **Crystallographic restriction, algebraic form.**  A unimodular integer `2 × 2`
matrix of finite order satisfies `A¹² = 1`; equivalently its order is one of
`1, 2, 3, 4, 6`: there are no fivefold or sevenfold lattice symmetries. -/
theorem pow_twelve_eq_one (A : Matrix (Fin 2) (Fin 2) ℤ) (hdet : A.det = 1)
    {n : ℕ} (hn : 1 ≤ n) (hA : A ^ n = 1) : A ^ 12 = 1 := by
  have hsq : A * A = A.trace • A - 1 := by rw [cayley_hamilton_two A, hdet, one_smul]
  have hcube : A ^ 3 = A * A * A := by rw [pow_succ, pow_two]
  rcases trace_mem_five_values A hdet hn hA with ht | ht | ht | ht | ht
  · -- trace `-2`: then `-A` has trace `2`, so `-A = 1` and `A = -1`
    have hneg : (-A) ^ (2 * n) = 1 := neg_pow_eq_one A hA
    have htr' : (-A).trace = 2 := by rw [Matrix.trace_neg, ht]; norm_num
    have h1 : (-A) = 1 :=
      eq_one_of_trace_two (-A) (det_neg_two A hdet) htr' (by omega) hneg
    have hA1 : A = -1 := by
      have := congrArg Neg.neg h1
      simpa using this
    rw [hA1]
    exact Even.neg_one_pow ⟨6, rfl⟩
  · -- trace `-1`: then `A³ = 1`
    have h3 : A ^ 3 = 1 := by
      rw [hcube, hsq, ht, sub_mul, smul_mul_assoc, one_mul, hsq, ht]
      simp [smul_sub]
    calc A ^ 12 = (A ^ 3) ^ 4 := by rw [← pow_mul]
      _ = 1 := by rw [h3, one_pow]
  · -- trace `0`: then `A² = -1`
    have h2 : A ^ 2 = -1 := by
      rw [pow_two, hsq, ht, zero_smul]
      abel
    calc A ^ 12 = (A ^ 2) ^ 6 := by rw [← pow_mul]
      _ = 1 := by rw [h2]; exact Even.neg_one_pow ⟨3, rfl⟩
  · -- trace `1`: then `A³ = -1`
    have h3 : A ^ 3 = -1 := by
      rw [hcube, hsq, ht, sub_mul, smul_mul_assoc, one_mul, hsq, ht]
      simp [smul_sub]
    calc A ^ 12 = (A ^ 3) ^ 4 := by rw [← pow_mul]
      _ = 1 := by rw [h3]; exact Even.neg_one_pow ⟨2, rfl⟩
  · -- trace `2`: then `A = 1`
    rw [eq_one_of_trace_two A hdet ht hn hA, one_pow]

/-- **There is no fivefold symmetry.**  A unimodular integer matrix with `A⁵ = 1` is the
identity: no wallpaper pattern has a fivefold rotation axis.  (`5` is coprime to
`12`, and `A¹² = 1`.) -/
theorem no_fivefold_symmetry (A : Matrix (Fin 2) (Fin 2) ℤ) (hdet : A.det = 1)
    (h5 : A ^ 5 = 1) : A = 1 := by
  have h12 : A ^ 12 = 1 := pow_twelve_eq_one A hdet (by norm_num) h5
  have h24 : A ^ 24 = 1 := by rw [show (24 : ℕ) = 12 * 2 by norm_num, pow_mul, h12, one_pow]
  have h25 : A ^ 25 = 1 := by rw [show (25 : ℕ) = 5 * 5 by norm_num, pow_mul, h5, one_pow]
  have hstep : A ^ 25 = A ^ 24 * A := by rw [← pow_succ]
  rw [h25, h24, one_mul] at hstep
  exact hstep.symm

/-- **Sixfold symmetry does occur**: the rotation by `60°` of the triangular lattice,
written in the lattice basis, is the integer matrix `!![0, -1; 1, 1]`.  Its order
is exactly `6`, so the bound of `pow_twelve_eq_one` is attained. -/
theorem hexagonal_rotation_pow_six :
    (!![0, -1; 1, 1] : Matrix (Fin 2) (Fin 2) ℤ) ^ 6 = 1 := by decide

theorem hexagonal_rotation_pow_three_ne_one :
    (!![0, -1; 1, 1] : Matrix (Fin 2) (Fin 2) ℤ) ^ 3 ≠ 1 := by decide

theorem hexagonal_rotation_pow_two_ne_one :
    (!![0, -1; 1, 1] : Matrix (Fin 2) (Fin 2) ℤ) ^ 2 ≠ 1 := by decide

theorem hexagonal_rotation_det :
    (!![0, -1; 1, 1] : Matrix (Fin 2) (Fin 2) ℤ).det = 1 := by
  simp [Matrix.det_fin_two_of]

end Crystallographic

/-! ## 4. The point group of the square lattice -/

section PointGroup

/-- Integer solutions of `a² + c² = 1`. -/
theorem int_sq_add_sq_eq_one {a c : ℤ} (h : a ^ 2 + c ^ 2 = 1) :
    (a = 1 ∧ c = 0) ∨ (a = -1 ∧ c = 0) ∨ (a = 0 ∧ c = 1) ∨ (a = 0 ∧ c = -1) := by
  have ha : -1 ≤ a ∧ a ≤ 1 := by constructor <;> nlinarith [sq_nonneg c, sq_nonneg a]
  have hc : -1 ≤ c ∧ c ≤ 1 := by constructor <;> nlinarith [sq_nonneg c, sq_nonneg a]
  obtain ⟨ha1, ha2⟩ := ha
  obtain ⟨hc1, hc2⟩ := hc
  interval_cases a <;> interval_cases c <;> simp_all

/-- The eight symmetries of the square lattice, as matrices. -/
def pointGroupSquare : Finset (Matrix (Fin 2) (Fin 2) ℤ) :=
  {!![1, 0; 0, 1], !![0, -1; 1, 0], !![-1, 0; 0, -1], !![0, 1; -1, 0],
   !![1, 0; 0, -1], !![-1, 0; 0, 1], !![0, 1; 1, 0], !![0, -1; -1, 0]}

/-- **The point group of the square lattice is the dihedral group of order 8**: the
integer matrices preserving the standard inner product are exactly the four
rotations by multiples of `90°` and the four reflections. -/
theorem lattice_isometry_cases (A : Matrix (Fin 2) (Fin 2) ℤ) (h : Aᵀ * A = 1) :
    A ∈ pointGroupSquare := by
  have e00 : A 0 0 ^ 2 + A 1 0 ^ 2 = 1 := by
    have := congrFun (congrFun h 0) 0
    simpa [Matrix.mul_apply, Fin.sum_univ_two, Matrix.one_apply, Matrix.transpose_apply,
      sq] using this
  have e11 : A 0 1 ^ 2 + A 1 1 ^ 2 = 1 := by
    have := congrFun (congrFun h 1) 1
    simpa [Matrix.mul_apply, Fin.sum_univ_two, Matrix.one_apply, Matrix.transpose_apply,
      sq] using this
  have e01 : A 0 0 * A 0 1 + A 1 0 * A 1 1 = 0 := by
    have := congrFun (congrFun h 0) 1
    simpa [Matrix.mul_apply, Fin.sum_univ_two, Matrix.one_apply, Matrix.transpose_apply]
      using this
  have hA : A = !![A 0 0, A 0 1; A 1 0, A 1 1] := by
    ext i j; fin_cases i <;> fin_cases j <;> rfl
  rcases int_sq_add_sq_eq_one e00 with ⟨h1, h2⟩ | ⟨h1, h2⟩ | ⟨h1, h2⟩ | ⟨h1, h2⟩ <;>
    rcases int_sq_add_sq_eq_one e11 with ⟨h3, h4⟩ | ⟨h3, h4⟩ | ⟨h3, h4⟩ | ⟨h3, h4⟩ <;>
      rw [h1, h2, h3, h4] at e01 hA <;>
        first
          | (rw [hA]; decide)
          | (exfalso; norm_num at e01)

theorem mem_pointGroupSquare_isometry (A : Matrix (Fin 2) (Fin 2) ℤ)
    (h : A ∈ pointGroupSquare) : Aᵀ * A = 1 := by
  fin_cases h <;> · ext i j; fin_cases i <;> fin_cases j <;> norm_num [Matrix.mul_apply,
    Fin.sum_univ_two, Matrix.one_apply]

/-- There are exactly eight of them. -/
theorem pointGroupSquare_card : pointGroupSquare.card = 8 := by decide

/-- Four of the eight are rotations (determinant `1`), four are reflections
(determinant `-1`). -/
theorem pointGroupSquare_rotations_card :
    (pointGroupSquare.filter (fun A => A.det = 1)).card = 4 := by decide

/-- The characterisation as a set equality. -/
theorem isometry_set_eq : {A : Matrix (Fin 2) (Fin 2) ℤ | Aᵀ * A = 1} = ↑pointGroupSquare := by
  ext A
  exact ⟨lattice_isometry_cases A, mem_pointGroupSquare_isometry A⟩

end PointGroup

end Tiling
